name: Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure and build project
      uses: threeal/cmake-action@main

  test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - name: Run tests
      run: ./build/chestillo_test
